version: "3"

services:
  mongo:
    image: bitnami/mongodb:latest
    environment: 
      - MONGODB_ROOT_PASSWORD=ab.cd1/1
      - MONGODB_USERNAME=nuclient1
      - MONGODB_PASSWORD=nuclient.1/1
      - MONGODB_DATABASE=nuClient
    volumes:
      - $PWD/data/:/bitnami
    networks:
      - database
    user: "0"
    container_name: nuclient_mongo
  mongo-express:
    image: mongo-express
    restart: always
    labels:
      - "traefik.backend=mongo-express"
      - "traefik.frontend.rule=Host:admindb.nuclient.es"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=8081"
      - "traefik.docker.network=web"
    links:
      - mongo
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=dxestion
      - ME_CONFIG_BASICAUTH_PASSWORD=Dxestion0180
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ab.cd1/1
    networks:
      - web
      - database
    container_name: mongo-express
  backend:
    build:
      context: ./backend
    links:
      - mongo
    labels:
      - "traefik.backend=nuclientbackend"
      - "traefik.frontend.rule=Host:backend.nuclient.es"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.docker.network=web"
      - "traefik.port=3000"
    depends_on:
      - mongo
    volumes:
      - $PWD/uploads/:/user/src/app/uploads
      - $PWD/logs/:/user/src/app/logs
    networks:
      - web
      - database
    container_name: nuclient_backend

  frontend-admin:
    build:
      context: ./frontend-admin-app
    links:
      - backend
    labels:
      - "traefik.backend=web-admin"
      - "traefik.frontend.rule=Host:admin.nuclient.es"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=80"
    depends_on:
      - mongo
      - backend
    networks:
      - web
    volumes:
      - $PWD/nginx_conf:/etc/nginx/conf.d
    container_name: nuclient_web-admin
  frontend-client:
    build:
      context: ./frontend-client-app
    links:
      - backend
    labels:
      - "traefik.backend=web-client"
      - "traefik.frontend.rule=Host:app.nuclient.es"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=80"
    depends_on:
      - mongo
      - backend
    networks:
      - web
    volumes:
      - $PWD/nginx_conf:/etc/nginx/conf.d
    container_name: nuclient_web-client
networks:
  web:
    external: true
  database:
    internal: true
