version: "3"

services:
  traefik:
    image: traefik:latest
    # command: --api --docker --docker.domain=nuclient.es:25501
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:traefik.nuclient.es:25501"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik/config/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/traefik/config/acme.json:/etc/traefik/acme/acme.json
      # - $PWD/ssl_certs/common:/etc/traefik/certs
    container_name: traefik
  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=dxestion
      - MONGO_INITDB_ROOT_PASSWORD=Dxestion0180
    volumes:
      - $PWD/data/:/data/db
    ports:
      - "27017:27017"
    networks:
      - database
    container_name: mongo
  mongo-express:
    image: mongo-express
    restart: always
    labels:
      - "traefik.backend=mongo-express"
      - "traefik.frontend.rule=Host:admindb.nuclient.es:25501"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=8081"
    links:
      - mongo
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=dxestion
      - ME_CONFIG_BASICAUTH_PASSWORD=Dxestion0180
    networks:
      - web
      - database
    container_name: mongo-express

  backend:
    build:
      context: ./backend
    links:
      - mongo
    labels:
      - "traefik.backend=backend"
      - "traefik.frontend.rule=Host:backend.nuclient.es:25501"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=3000"
    depends_on:
      - mongo
    volumes:
      - $PWD/uploads/:/data/uploads
      - $PWD/logs/:/data/logs
    networks:
      - web
      - database
    container_name: backend

  frontend-admin:
    build:
      context: ./frontend-admin-app
    links:
      - backend
    labels:
      - "traefik.backend=web-admin"
      - "traefik.frontend.rule=Host:admin.nuclient.es:25501"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=80"
    depends_on:
      - mongo
      - backend
    networks:
      - web
    volumes:
      - $PWD/nginx_conf:/etc/nginx/conf.d
    container_name: web-admin
  frontend-client:
    build:
      context: ./frontend-client-app
    links:
      - backend
    labels:
      - "traefik.backend=web-client"
      - "traefik.frontend.rule=Host:nuclient.es:25501, www.nuclient.es:25501, web.nuclient.es:25501"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=80"
    depends_on:
      - mongo
      - backend
    networks:
      - web
    volumes:
      - $PWD/nginx_conf:/etc/nginx/conf.d
    container_name: web-client
networks:
  web:
    external: true
  database:
    internal: true
