version: '3'

services:
  traefik:
    image: traefik:latest
    # command: --api --docker --docker.domain=dxestionmail.com
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:traefik.dxestionmail.com"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/traefik/acme.json:/etc/traefik/acme/acme.json
    container_name: traefik

  mongo:
    image: mongo
    volumes:
      - $PWD/data/:/data/db
    ports:
      - "27017:27017"
    networks:
      - web
    container_name: mongo

  backend:
    build: 
      context: ./backend
    links:
      - mongo
    labels:
      - "traefik.backend=backend"
      - "traefik.frontend.rule=Host:backend.dxestionmail.com"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=3000"
    depends_on:
      - mongo
    networks:
      - web
    container_name: backend

  frontend-admin:
    build: 
      context: ./frontend-admin-app
    links:
      - backend
    labels:
      - "traefik.backend=web-admin"
      - "traefik.frontend.rule=Host:admin.dxestionmail.com"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=80"
    depends_on:
      - mongo
      - backend
    networks:
      - web
    volumes:
      # - $PWD/ssl_certs/frontend-app:/etc/nginx/ssl
      - $PWD/nginx_conf:/etc/nginx/conf.d
    container_name: web-admin
  frontend-client:
    build: 
      context: ./frontend-client-app
    links:
      - backend
    labels:
      - "traefik.backend=web-client"
      - "traefik.frontend.rule=Host:dxestionmail.com, www.dxestionmail.com, web.dxestionmail.com"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=80"
    depends_on:
      - mongo
      - backend
    networks:
      - web
    volumes:
      - $PWD/nginx_conf:/etc/nginx/conf.d
    container_name: web-client
networks:
  web:
    external: true