version: '3'

services:
  mongo:
    image: mvertes/alpine-mongo
    restart: always
    volumes:
      - $PWD/data/:/data/db
    ports:
      - '27017:27017'
    networks:
      - database
    container_name: mongo
  mongo-express:
    image: mongo-express
    restart: always
    links:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=dxestion
      - ME_CONFIG_BASICAUTH_PASSWORD=Dxestion0180
    ports:
      - '8081:8081'
    networks:
      - web
      - database
    container_name: mongo-express
  backend:
    build:
      context: ./backend
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - $PWD/uploads/:/user/src/app/uploads
      - $PWD/logs/:/user/src/app/logs
    ports:
      - '3000:3000'
    networks:
      - web
      - database
    container_name: backend
  # frontend-admin:
  #   build:
  #     context: ./frontend-admin-app
  #   links:
  #     - backend
  #   depends_on:
  #     - mongo
  #     - backend
  #   ports:
  #     - '80:80'
  #   networks:
  #     - web
  #   volumes:
  #     - $PWD/nginx_conf:/etc/nginx/conf.d
  #   container_name: web-admin
  # frontend-client:
  #   build:
  #     context: ./frontend-client-app
  #   links:
  #     - backend
  #   depends_on:
  #     - mongo
  #     - backend
  #   ports:
  #     - '90:80'
  #   networks:
  #     - web
  #   volumes:
  #     - $PWD/nginx_conf:/etc/nginx/conf.d
  #   container_name: web-client
networks:
  web:
    external: true
  database:
    internal: true
