version: "3"

services:
  mongo:
    image: mvertes/alpine-mongo
    #environment: 
      #- MONGO_INITDB_ROOT_USERNAME=dxestion
      #- MONGO_INITDB_ROOT_PASSWORD=Dxestion0180
    volumes:
      - $PWD/data/:/data/db
    ports:
      - "27017:27017"
    networks:
      - web
    container_name: nuclient_mongo
  backend:
    build:
      context: ./backend
    links:
      - mongo
    labels:
      - "traefik.backend=nuclientbackend"
      - "traefik.frontend.rule=Host:backendnuclient.serantes.pro"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=3000"
    depends_on:
      - mongo
    volumes:
      - $PWD/uploads/:/data/uploads
      - $PWD/logs/:/data/logs
    networks:
      - web
    container_name: nuclient_backend

  frontend-admin:
    build:
      context: ./frontend-admin-app
    links:
      - backend
    labels:
      - "traefik.backend=web-admin"
      - "traefik.frontend.rule=Host:adminnuclient.serantes.pro"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=80"
    depends_on:
      - mongo
      - backend
    networks:
      - web
    volumes:
      - $PWD/nginx_conf:/etc/nginx/conf.d
    container_name: nuclient_web-admin
  frontend-client:
    build:
      context: ./frontend-client-app
    links:
      - backend
    labels:
      - "traefik.backend=web-client"
      - "traefik.frontend.rule=Host:nuclient.serantes.pro, www.nuclient.serantes.pro, webnuclient.serantes.pro"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=80"
    depends_on:
      - mongo
      - backend
    networks:
      - web
    volumes:
      - $PWD/nginx_conf:/etc/nginx/conf.d
    container_name: nuclient_web-client
networks:
  web:
    external: true