version: '3'

services:
  traefik:
    image: traefik:v1.7
    # command: --api --docker --docker.domain=nuclient.es
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
      - database
    labels:
      - "traefik.frontend.rule=Host:traefik.nuclient.es"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/config/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/config/acme.json:/etc/traefik/acme/acme.json
      # - $PWD/ssl_certs/common:/etc/traefik/certs
    container_name: traefik
networks:
  web:
    external: true
  database:
    internal: true